config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'dashboard/index'
    resources :users
    resources :articles do
      resources :comments
    end
  end

  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  #resources :comments
  resources :users, expect: [:new]
  resources :articles do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  enum status: [:published, :unpublished, :not_set]
  validates :comment, presence: true, length: {minimum: 3, maximum: 300}
  belongs_to :article
  belongs_to :user


end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :set_article, only: [:create, :update]
  def create
    @comment = @article.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.status = "unpublished"

    if @comment.save
      flash[:success] = "Comment was added!"
      redirect_to admin_article_path(@article)

    else
      flash[:success] = "Comment was not added"
      redirect_to admin_article_path(@article)
    end
  end
  def update
    @comment = Comment.find(params[:article_id])
    if @comment.status == "published"
      @comment.update(status: "unpublished")
      flash[:success] = "Comment was published"
      redirect_to request.referrer
    else
      @comment.update(status: "published")
      flash[:success] = "Comment was unpublished"
      redirect_to request.referrer
    end
  end
  def edit
  end
  def destroy
    @comment = Comment.find(params[:article_id])
    @comment.destroy
    flash[:success] = "Comment was deleted"
    redirect_to request.referrer
  end
  def set_article
    @article = Article.find(params[:article_id])
  end
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article, only: [:create, :update]
  def create
   @comment = @article.comments.create(comment_params)
   @comment.user_id = current_user.id
   @comment.status = "unpublished"

   if @comment.save
     flash[:success] = "Udało się dodać komentarz! Poczekaj na zaakceptowanie go przez administratora"
     redirect_to @article

  else
   redirect_to root_path
     end
  end
  def update
    @comment = Comment.find(params[:article_id])
    if @comment.status == "published"
      @comment.update(status: "unpublished")
      flash[:success] = "Comment was published"
      redirect_to request.referrer
    else
      @comment.update(status: "published")
      flash[:success] = "Comment was unpublished"
      redirect_to request.referrer
    end
  end
  def edit
  end
  def set_article
    @article = Article.find(params[:article_id])
  end
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_comment.html.erb
<table class = "table table-striped table-hover">
  <thead>
  <tr>
    <th>Comment</th>
    <th>Status</th>

    <th colspan="2"> </th>
  </tr>
  </thead>
  <tbody>
  <% @comments.each do |comment| %>
    <tr>
      <td> <%= comment.comment %></td>
      <td> <%= comment.status %></td>
      <td> <%= link_to 'Edit', edit_admin_article_comment_path(comment) %></td>
      <td> <%= link_to 'Destroy', admin_article_comment_path(comment), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <td><% if comment.status ==  "published" %>
          <%= link_to "Unpublish", admin_article_comment_path(comment), method: :put, data: { confirm: "You sure?"} %>
        <% end %>
        <% if comment.status ==  "unpublished" %>
          <%= link_to "Publish", admin_article_comment_path(comment), method: :put, data: {confirm: "You sure?"}%>
        <% end %>
      </td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/comments/_form.html.erb
<%= render 'shared/errors', obj: @comment %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for([:admin,@article,@comment], :html => {class: "form-horizontal", role: "form"}) do |f| %>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :comment %>
        </div>
        <div class="col-sm-6">
          <%= f.text_area :comment, rows: 5, class: "form-control", placeholder: "Comment" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
          <%= f.submit class: 'btn btn-primary btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>