config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'dashboard/index'
    resources :users
    resources :articles do
      resources :comments
    end
  end

  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  #resources :comments
  resources :users, expect: [:new]
  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
  accepts_nested_attributes_for :comments
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  def new
    @article = Article.new
  end
  def create
    #render plain: current_user.id
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      flash[:success] = "Article was successfully created!"
      redirect_to admin_articles_path
    else
      render 'new'
    end
  end
  def show
    @comment = Comment.new
    @comments = @article.comments
  end
  def edit

  end
  def update
    if @article.update(article_params)
      flash[:success] = "Article was updated"
      redirect_to admin_articles_path
    else
      flash[:success] = "Article was not updated"
      render 'edit'
    end
  end
  def index
    @article = Article.all
  end
  def destroy
    @article.destroy
    flash[:success] = "Article was deleted"
    redirect_to admin_articles_path
  end
  def set_article
    @article = Article.find(params[:id])
  end
  private
  def article_params
    params.require(:article).permit(:title,:description)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  def new
    if current_user
       @article = Article.new
    else
      redirect_to articles_path
    end
  end
  def create
   #render plain: current_user.id
    if current_user
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      flash[:success] = "Article was successfully created!"
      redirect_to @article
    else
     render 'new'
    end
    else
      redirect_to root_path
    end
  end
  def show
    @comment = Comment.new
    @comments = @article.comments
  end
  def edit
    if current_user

    else
      redirect_to article_path(@article.id)
    end

  end
  def update
    if @article.update(article_params) && current_user.id == @article.user_id
      flash[:success] = "Article was updated"
      redirect_to @article
    else
      flash[:success] = "Article was not updated"
      render 'edit'
    end
  end
  def index
    @article = Article.all
  end
  def destroy
    if current_user && current_user.id == @article.user_id
    @article.destroy
    flash[:success] = "Article was deleted"
    redirect_to articles_path
    end
  end
  def set_article
    @article = Article.find(params[:id])
  end
  private
    def article_params
      params.require(:article).permit(:title,:description)
    end
end

app/views/admin/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for([:admin,@article], :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-6">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-6">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
          <%= f.submit class: 'btn btn-primary btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>

app/views/admin/articles/index.html.erb
<h1 align="center">Manage Articles</h1>
<%= link_to 'Add Article', new_admin_article_path %>
<table class = "table table-striped table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th colspan="2"> </th>
      </tr>
    </thead>
    <tbody>
    <% @article.each do |article| %>
    <tr>
      <td> <%= article.title %></td>
      <td> <%= article.description %></td>
      <td> <%= link_to 'Show', admin_article_path(article)%></td>
      <td> <%= link_to 'Edit', edit_admin_article_path(article) %></td>
      <td> <%= link_to 'Destroy', admin_article_path(article), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>
    </tbody>
  </table>

app/views/admin/articles/new.html.erb
  <h1>Create an article</h1>
  <%= render 'form' %>

app/views/admin/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<h4 class="article-title center" ><%= link_to @article.user.username, admin_user_path(@article.user) %></h4>
<h4 class="center"><strong>Description:</strong></h4>
<hr>
<h5 class="center"><%= @article.description%></h5>
  <ul>
    <%= render partial: 'admin/comments/form'%>
    <%= render partial: 'admin/comments/comment'%>
  </ul>


</div>