config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'dashboard/index'
    resources :users
    resources :articles do
      resources :comments
    end
  end

  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  #resources :comments
  resources :users, expect: [:new]
  resources :articles do
    resources :comments
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_many :comments
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, length: {maximum: 105}, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
            before_save {self.email = email.downcase}
  validates :password, presence: true, length: {minimum: 8}
  validates :password, confirmation: { case_sensitive: true }
  has_secure_password
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account created!"
      redirect_to admin_users_path(@user)
    else
      render 'new'
    end
  end
  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to admin_users_path
    else
      flash[:success] = "User was not updated"
      render 'edit'
    end
  end
  def edit
  end
  def show
  end
  def destroy
    @user.destroy
    flash[:success] = "User was deleted"
    redirect_to admin_users_path
  end
  def set_user
    @user = User.find(params[:id])
  end
  def destroy
    @comment.destroy
    flash[:success] = "Comment was deleted"
    redirect_to articles_path
  end
  def index
    @user = User.all
  end
  private
  def user_params
    params.require(:user).permit(:username,:email,:password,:password_confirmation,:role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    @user.role = "user"
    if @user.save
      flash[:success] = "Welcome to the  blog #{@user.username}"
      session[:user_id] = @user.id
      redirect_to users_path(@user)
    else
      render 'new'
    end
  end
  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    end
  end
  def edit
  end
  def show
  end
  def set_user
    @user = User.find(params[:id])
  end
  def index
    @user = User.all
  end
  private
  def user_params
    params.require(:user).permit(:username,:email,:password,:password_confirmation)
  end

end

app/views/admin/users/_form.html.erb
<%= render 'shared/errors', obj: @user %><div class="row">
  <div class="col-xs-12">
    <%= form_for([:admin,@user], :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-7">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-7">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-7">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password_confirmation %>
        </div>
        <div class="col-sm-7">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :role %>
        </div>
        <div class="col-sm-7">
          <%= f.select :role, [['Admin','admin'],['User','user']], {class: "form-control"} %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-7">
          <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-2">
      [ <%= link_to 'Cancel request and Return to Articles Listing', articles_path %> ]
    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<h1 align="center">Edit User Account</h1>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1 align="center">Manage Users</h1>
<%= link_to 'Create User', new_admin_user_path %>
<table class = "table table-striped table-hover">
  <thead>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Role</th>

    <th colspan="2"> </th>
  </tr>
  </thead>
  <tbody>
  <% @user.each do |user| %>
    <tr>
      <td> <%= user.username %></td>
      <td> <%= user.email %></td>
      <td> <%= user.role %></td>
      <td> <%= link_to 'Show', admin_user_path(user)%></td>
      <td> <%= link_to 'Edit', edit_admin_user_path(user) %></td>
      <td> <%= link_to 'Destroy', admin_user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1 align="center">Signup</h1>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-5 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4><%= render 'shared/article', obj: @user.articles %>